<?php


return [
    'phone' => ['smartphone', 'cellphone', 'mobile', 'handset', 'device', 'gadget', 'телефон', 'смартфон', 'мобильник', 'аппарат'],
    'computer' => ['pc', 'laptop', 'desktop', 'workstation', 'machine', 'device', 'компьютер', 'пк', 'ноутбук'],
    'watch' => ['timepiece', 'timekeeper', 'wristwatch', 'chronometer', 'clock', 'часы', 'наручные часы', 'хронометр'],
    'camera' => ['photographic camera', 'digital camera', 'photocamera', 'камера', 'фотоаппарат', 'цифровая камера'],
    'appliance' => ['device', 'gadget', 'tool', 'instrument', 'equipment', 'устройство', 'прибор', 'аппарат'],
    'microchip' => ['chip', 'integrated circuit', 'IC', 'microprocessor', 'микросхема', 'интегральная схема', 'микропроцессор'],
    'circuit' => ['diagram', 'schematic', 'board', 'circuitry', 'электрическая схема', 'схема', 'плата'],
    'remote' => ['control', 'clicker', 'controller', 'телевизионный пульт', 'пульт', 'управление'],
    'battery' => ['cell', 'power source', 'rechargeable', 'batteries', 'батарея', 'элемент питания', 'аккумулятор', 'перезаряжаемый'],
    'display' => ['screen', 'monitor', 'panel', 'display', 'экран', 'монитор', 'панель'],
    'speaker' => ['loudspeaker', 'audio output', 'sound system', 'speaker', 'динамик', 'звуковая система'],
    'microphone' => ['mic', 'audio input', 'microphone', 'микрофон', 'звуковой вход'],
    'wire' => ['cable', 'cord', 'wiring', 'wire', 'провод', 'кабель', 'проводка'],
    'switch' => ['toggle', 'lever', 'button', 'switch', 'переключатель', 'выключатель', 'кнопка'],
    'antenna' => ['aerial', 'receiver', 'transmitter', 'antenna', 'антенна', 'приемник', 'передатчик'],
    'connector' => ['plug', 'jack', 'socket', 'connector', 'разъем', 'гнездо'],
    'resistor' => ['ohmic', 'resistance', 'variable resistor', 'resistor', 'резистор', 'переменный резистор'],
    'capacitor' => ['condenser', 'capacitance', 'variable capacitor', 'capacitor', 'конденсатор', 'переменный конденсатор'],
    'inductor' => ['coil', 'reactor', 'choke', 'inductor', 'индуктор', 'катушка'],
    'diode' => ['rectifier', 'semiconductor', 'diode', 'диод', 'полупроводник'],
    'transistor' => ['bipolar junction transistor', 'field-effect transistor', 'transistor', 'транзистор', 'биполярный транзистор', 'транзистор с полевым эффектом'],
    'fuse' => ['circuit protection', 'safety device', 'fuse', 'предохранитель', 'защитное устройство'],
    'motor' => ['engine', 'electric motor', 'servo', 'motor', 'двигатель', 'электродвигатель', 'сервомотор'],
    'valve' => ['gate', 'solenoid', 'valve', 'клапан', 'соленоид'],
    'encoder' => ['rotary encoder', 'linear encoder', 'encoder', 'кодер', 'вращательный кодер', 'линейный кодер'],
    'sensor' => ['proximity sensor', 'temperature sensor', 'pressure sensor', 'sensor', 'датчик', 'датчик близости', 'датчик температуры', 'датчик давления'],
    'actuator' => ['linear actuator', 'solenoid', 'actuator', 'привод', 'линейный привод', 'соленоид'],
    'pcb' => ['printed circuit board', 'circuit board', 'pcb', 'печатная плата', 'плата'],
    'relay' => ['electromechanical relay', 'solid-state relay', 'relay', 'реле', 'электромеханическое реле', 'твердотельное реле', 'электромагнитное реле', 'переключение', 'управление'],
    'controller' => ['microcontroller', 'programmable logic controller', 'controller', 'контроллер', 'микроконтроллер', 'программируемый логический контроллер'],
    'module' => ['board', 'circuit', 'module', 'модуль', 'плата', 'схема'],
    'kit' => ['set', 'package', 'kit', 'набор', 'комплект', 'пакет'],
    'device' => ['gadget', 'tool', 'instrument', 'equipment', 'device', 'устройство', 'прибор'],
    'adapter' => ['converter', 'connector', 'adapter', 'переходник', 'конвертер'],
    'component' => ['part', 'element', 'компонент', 'часть'],
    'interface' => ['user interface', 'интерфейс', 'пользовательский интерфейс'],
    'protocol' => ['communication protocol', 'протокол', 'протокол связи'],
    'logic' => ['logical operation', 'логика', 'логическая операция'],
    'algorithm' => ['computational algorithm', 'алгоритм', 'вычислительный алгоритм'],
    'software' => ['application', 'программное обеспечение', 'приложение'],
    'firmware' => ['embedded software', 'прошивка', 'встроенное программное обеспечение'],
    'network' => ['network', 'communication network', 'сеть', 'сетевое взаимодействие'],
    'communication' => ['data communication', 'связь', 'передач', 'коммуникация', 'передача данных'],
];

